name: Generate Snake Animation

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write  # Required to allow pushing changes

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository  # ✅ Add this as the first step
        uses: actions/checkout@v4

      - name: Generate GitHub Contribution Snake
        uses: Platane/snk@v3
        with:
          github_user_name: mohitdubey991735
          outputs: |
            ./output/github-contribution-grid-snake.svg

      - name: Push the generated SVG
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: "Generate contribution snake"
          add: "output/github-contribution-grid-snake.svg"
